# Generated by Django 4.2.8 on 2023-12-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_posts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
